failed to hide the secrets
I tired to keep the constructor internal, but this ends with the same compile error:
"This contract does not implement all functions and thus cannot be created."
hmm